name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pioEnv:
          - espair1
          - espair2
          - espair3
          # - espair4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Generate secrets.h
        run: |
          echo 'const char *ssid = "Foo";' > src/secrets.h
          echo 'const char *password = "Bar";' >> src/secrets.h

      - name: Build PlatformIO Project
        run: |
          pio run -e ${{ matrix.pioEnv }}

      - name: Publish firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pioEnv }}
          path: .pio/build/${{ matrix.pioEnv }}/firmware.bin
